[project]
name = "rag-eval-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Zaid", email = "gazaidgg@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "nltk>=3.10.3",
    "openai>=3.16.2",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag-eval-project = "rag_eval_project:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
